version: "3"
services:
    transcription_db:
        image: mysql:8.0.32
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "transcription_db"
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/mysql/transcription_data:/var/lib/mysql

    upload_db:
        image: mysql:8.0.32
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "upload_db"
        ports:
            - "3307:3306"
        volumes:
            - ./.docker/mysql/upload_data:/var/lib/mysql

    email_db:
        image: mysql:8.0.32
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "email_db"
        ports:
            - "3308:3306"
        volumes:
            - ./.docker/mysql/email_data:/var/lib/mysql

    redis:
        image: redis

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"

    transcription_service:
        build:
            context: .
            dockerfile: ./.docker/php/transcription-service/Dockerfile
        user: user:user
        volumes:
            - ./transcription-service:/var/www/html
            - ./.ci/transcription-service/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.ci/transcription-service/ports.conf:/etc/apache2/ports.conf
            - ./.ci/transcription-service/interface.conf:/etc/apache2/sites-enabled/interface.conf
        depends_on:
            - transcription_db
        ports:
            - "9055:9055"
        networks:
            - video_transcription

    upload_service:
        build:
            context: .
            dockerfile: ./.docker/php/upload-service/Dockerfile
        user: user:user
        volumes:
            - ./upload-service:/var/www/html
            - ./.ci/upload-service/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.ci/upload-service/ports.conf:/etc/apache2/ports.conf
            - ./.ci/upload-service/interface.conf:/etc/apache2/sites-enabled/interface.conf
        depends_on:
            - upload_db
        ports:
            - "9056:9055"
        networks:
            - video_transcription

    email_service:
        build:
            context: .
            dockerfile: ./.docker/php/email-service/Dockerfile
        user: user:user
        volumes:
            - ./email-service:/var/www/html
            - ./.ci/email-service/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.ci/email-service/ports.conf:/etc/apache2/ports.conf
            - ./.ci/email-service/interface.conf:/etc/apache2/sites-enabled/interface.conf
        environment:
            XDEBUG_CONFIG: client_host=${MYIP}
            DEBUG: 1
        depends_on:
            - email_db
        ports:
            - "9057:9055"
        networks:
            - video_transcription

networks:
    video_transcription:
        driver: bridge