version: "3"
services:

    transcription_service:
        build:
            context: .
            dockerfile: ./.docker/php/transcription-service/Dockerfile
        user: 1000:1000
        volumes:
            - ./:/var/www/html
            - ./.ci/transcription-service/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.ci/transcription-service/ports.conf:/etc/apache2/ports.conf
            - ./.ci/transcription-service/interface.conf:/etc/apache2/sites-enabled/interface.conf
        environment:
            XDEBUG_CONFIG: client_host=${MYIP}
            DEBUG: 1
        ports:
            - "9055:9055"
